# Generated by Django 3.0.4 on 2020-07-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('price', models.FloatField()),
                ('pieces', models.IntegerField(default=6)),
                ('instructions', models.CharField(default='Jain Option Available', max_length=250)),
                ('image', models.ImageField(default='default.png', upload_to='images/')),
                ('labels', models.CharField(blank=True, choices=[('BestSeller', 'BestSeller'), ('New', 'New'), ('Spicy', 'Spicy')], max_length=25)),
                ('label_colour', models.CharField(blank=True, choices=[('danger', 'danger'), ('success', 'success'), ('primary', 'primary'), ('info', 'info')], max_length=15)),
                ('slug', models.SlugField(default='sushi_name')),
            ],
        ),
    ]
