# Generated by Django 3.0.4 on 2020-07-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='cart_items',
        ),
    ]
