# Generated by Django 3.0.4 on 2020-07-25 21:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_cartitems_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 25, 21, 24, 20, 14250, tzinfo=utc)),
        ),
    ]
