# Generated by Django 3.0.4 on 2020-07-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200726_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'Cart Item', 'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AddField(
            model_name='cartitems',
            name='status',
            field=models.CharField(blank=True, choices=[('Ordered', 'Ordered'), ('Completed', 'Completed')], max_length=15),
        ),
    ]
