# Generated by Django 3.0.4 on 2020-07-27 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_cartitems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
