# Generated by Django 3.0.4 on 2020-08-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rslug',
            field=models.SlugField(),
        ),
    ]
